


package Homework2014.BridgeSegment.pchourasia;

import simView.*;

import java.awt.*;

import Homework2014.BridgeSegment.*;
//import java.io.*;
//import genDevs.modeling.*;
//import genDevs.simulation.*;
//import GenCol.*;


public class bridgeSystem extends AbstractBridgeSystem{


public bridgeSystem(){
    this("bridgeSys");
}

public bridgeSystem(String nm){
    super(nm);
    bridgeSystemConstruct();
}

public void bridgeSystemConstruct(){

    this.addOutport("EastboundOut");
    this.addOutport("WestboundOut");

    ViewableAtomic east_car_genr = new eastcarGenr("eastcarGenr",12);
    ViewableAtomic west_car_genr = new westcarGenr("westcarGenr",30);
    ViewableAtomic bridgesegment1 = new bridgeSegment("bridgesegment1",AbstractBridgeSystem.BridgeSystemSetting.Bridge1InitialState, AbstractBridgeSystem.BridgeSystemSetting.Bridge1TrafficLightDurationTime);
    ViewableAtomic bridgesegment2 = new bridgeSegment("bridgesegment2",AbstractBridgeSystem.BridgeSystemSetting.Bridge2InitialState, AbstractBridgeSystem.BridgeSystemSetting.Bridge2TrafficLightDurationTime);
    ViewableAtomic bridgesegment3 = new bridgeSegment("bridgesegment3",AbstractBridgeSystem.BridgeSystemSetting.Bridge3InitialState, AbstractBridgeSystem.BridgeSystemSetting.Bridge3TrafficLightDurationTime);
    ViewableAtomic trand = new Transducer();

     add(east_car_genr);
     add(bridgesegment1);
     add(bridgesegment2);
     add(bridgesegment3);
     add(west_car_genr);
     add(trand);


     addCoupling(east_car_genr,"out",bridgesegment3,"EastcarIn");
     addCoupling(west_car_genr,"out",bridgesegment1,"WestcarIn");
     addCoupling(bridgesegment1,"EastcarOut",this,"EastboundOut");
     addCoupling(bridgesegment1,"WestcarOut", bridgesegment2,"WestcarIn");
     addCoupling(bridgesegment2,"EastcarOut", bridgesegment1,"EastcarIn");
     addCoupling(bridgesegment2,"WestcarOut", bridgesegment3,"WestcarIn");
     addCoupling(bridgesegment3,"EastcarOut", bridgesegment2,"EastcarIn");
     addCoupling(bridgesegment3,"WestcarOut",this,"WestboundOut");
     addCoupling(bridgesegment1,"EastcarOut",trand,"WestboundOut");
     addCoupling(bridgesegment3,"WestcarOut",trand,"EastboundOut");
     addCoupling(bridgesegment1,"WestcarOut",trand,"Bridge1_WestOut");
     addCoupling(bridgesegment2,"WestcarOut",trand,"Bridge2_WestOut");
     addCoupling(bridgesegment3,"EastcarOut",trand,"Bridge3_EastOut");
     addCoupling(bridgesegment2,"EastcarOut",trand,"Bridge3_EastOut");
}


    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(934, 453);
        if((ViewableComponent)withName("westcarGenr")!=null)
             ((ViewableComponent)withName("westcarGenr")).setPreferredLocation(new Point(0, 101));
        if((ViewableComponent)withName("transducer")!=null)
             ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(320, 44));
        if((ViewableComponent)withName("bridgesegment2")!=null)
             ((ViewableComponent)withName("bridgesegment2")).setPreferredLocation(new Point(297, 281));
        if((ViewableComponent)withName("bridgesegment1")!=null)
             ((ViewableComponent)withName("bridgesegment1")).setPreferredLocation(new Point(172, 157));
        if((ViewableComponent)withName("eastcarGenr")!=null)
             ((ViewableComponent)withName("eastcarGenr")).setPreferredLocation(new Point(581, 306));
        if((ViewableComponent)withName("bridgesegment3")!=null)
             ((ViewableComponent)withName("bridgesegment3")).setPreferredLocation(new Point(465, 181));
    }
}
